#!/bin/sh

# You may invoke this like so:
# ./launch_x11vnc -clip 1024x768+0+0
# ./launch_x11vnc -clip xinerama1

exec x11vnc -coe localhost -rfbport 0 -nopw -nocursor -nosel -viewonly -deferupdate none "$@" -geometry 1024x768
